version: '3.8'

services:
  bot:
    build: .
    container_name: telegram-antispam-bot
    restart: unless-stopped
    env_file: .env
    volumes:
      - .:/app
    # Если боту нужен доступ к внешним ресурсам или API
    network_mode: host
    # Или можно использовать стандартные сети Docker
    # networks:
    #   - telegram-antispam-bot-network

# networks:
#   telegram-antispam-bot-network:
#     driver: bridge
